
[client]
	#Toggles the lantern glow effect, which may look bad with certain shaders.
	glow_effect = true
	#Enable camera shaking during certain mob attacks and abilities.
	do_camera_shake = false
	#Play boss battle themes during boss encounters.
	play_boss_music = false
	#Use custom boss health bar textures, if the boss has them.
	custom_boss_bar = false
	#Use custom player animations.
	custom_player_anims = true

